apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-pod
  template:
    name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-pod
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80